modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Better%20Conduit%20Placement"
logoFile="icon.png"

[[mods]]
modId="betterconduitplacement"
version="3.0"
displayName="Better Conduit Placement"
displayURL="https://curseforge.com/minecraft/mc-mods/better-conduit-placement"
authors="Rick South"
description='''Place conduits in front of you, place blocks by clicking the conduit and other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.betterconduitplacement]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"